import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react'
import cytoscape from 'cytoscape'
import katex from 'katex'
import MiniSearch from 'minisearch'
import { Link, NavLink, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom'
import type { AppData } from './lib/data'
import type { GraphNode, Problem } from './types'

const nav = [{ to: '/', label: '总览' }, { to: '/graph', label: '知识图谱' }, { to: '/exams', label: '真题档案' }, { to: '/statistics', label: '统计研究' }, { to: '/about', label: '来源与方法' }]

function Shell({ children, data }: { children: ReactNode; data: AppData }) {
  const [query, setQuery] = useState(''); const navigate = useNavigate(); const location = useLocation()
  const search = useMemo(() => { const m = new MiniSearch({ fields: ['title', 'subtitle', 'text'], storeFields: ['title', 'subtitle', 'kind', 'id'] }); m.addAll(data.search); return m }, [data.search])
  const submit = (event: React.FormEvent) => { event.preventDefault(); const hit = search.search(query, { prefix: true, fuzzy: 0.2 })[0] as { id?: string; kind?: string } | undefined; if (hit) navigate(hit.kind === 'problem' ? `/exams/${hit.id}` : `/knowledge/${hit.id}`); else navigate(`/exams?q=${encodeURIComponent(query)}`) }
  return <div className="app"><header className="topbar"><Link to="/" className="brand"><span className="brand-mark">χ</span><span>化学竞赛<br /><b>知识图谱</b></span></Link><form className="search" onSubmit={submit}><span aria-hidden="true">⌕</span><input aria-label="搜索知识点、题目或年份" value={query} onChange={event => setQuery(event.target.value)} placeholder="搜索知识点、题目或年份" /><button type="submit" className="search-submit">搜索</button></form><div className="top-actions"><span className="version">数据 2026.08</span><button className="display-toggle" onClick={() => document.documentElement.classList.toggle('dark')}>切换显示</button></div></header><nav className="nav" aria-label="主导航">{nav.map(item => <NavLink key={item.to} to={item.to} end={item.to === '/'} className={({ isActive }) => isActive ? 'active' : ''}>{item.label}</NavLink>)}</nav><main className="content">{children}</main><footer><span>化学竞赛知识图谱</span><span>{data.statistics.totalExams} 组考试 · {data.statistics.totalProblems} 条题目元数据</span><Link to="/about">查看资料说明</Link></footer></div>
}

function OverviewGraph({ data }: { data: AppData }) {
  const container = useRef<HTMLDivElement>(null); const [selected, setSelected] = useState<GraphNode | null>(null); const navigate = useNavigate()
  useEffect(() => { if (!container.current) return; const cy = cytoscape({ container: container.current, elements: [...data.graph.nodes.map(node => ({ data: node })), ...data.graph.edges.map(edge => ({ data: edge }))], style: [{ selector: 'node', style: { 'background-color': (element: any) => data.taxonomy.disciplines.find(d => d.id === element.data('discipline'))?.color || '#5575b8', label: 'data(label)', color: '#183b4d', 'font-size': 10, 'text-wrap': 'wrap', 'text-max-width': 75, 'text-valign': 'bottom', 'text-margin-y': 7, width: 34, height: 34, 'border-width': 2, 'border-color': '#fff' } }, { selector: 'edge', style: { width: 1.4, 'line-color': '#aec0c5', 'target-arrow-shape': 'triangle', 'target-arrow-color': '#aec0c5', 'curve-style': 'bezier' } }, { selector: ':selected', style: { 'border-width': 4, 'border-color': '#f4a261' } }] as any, layout: { name: 'cose', animate: false, padding: 24 } }); cy.on('tap', 'node', event => setSelected(event.target.data() as GraphNode)); return () => cy.destroy() }, [data])
  const neighbors = selected ? data.graph.edges.filter(edge => edge.source === selected.id || edge.target === selected.id) : []
  return <section className="overview-map"><div className="overview-map-head"><div><p className="eyebrow">可探索的知识网络</p><h2>知识节点与关系</h2><p>点击节点查看相邻知识；搜索栏可以直接定位节点或题目。</p></div><Link className="text-link" to="/graph">打开完整图谱</Link></div><div className="overview-map-body"><div ref={container} className="overview-cy" aria-label="化学知识网络总览" /><aside className="overview-selection">{selected ? <><p className="eyebrow">已选择</p><h3>{selected.label}</h3><p className="muted">{data.taxonomy.disciplines.find(item => item.id === selected.discipline)?.name}</p><h4>相邻知识</h4><ul className="relation-list">{neighbors.slice(0, 5).map(edge => { const other = data.graph.nodes.find(node => node.id === (edge.source === selected.id ? edge.target : edge.source)); return <li key={edge.id}><span className="relation-type">{data.taxonomy.relations.find(item => item.id === edge.relation)?.name || edge.relation}</span><button onClick={() => setSelected(other || null)}>查看 {other?.label}</button></li> })}</ul><button className="secondary full" onClick={() => navigate(`/knowledge/${selected.id}`)}>查看知识详情</button></> : <><h3>选择一个节点</h3><p className="muted">右侧会显示相邻知识、关系类型和详情链接。</p></>}</aside></div></section>
}

function Home({ data }: { data: AppData }) {
  const navigate = useNavigate(); const topics = data.graph.nodes.filter(node => node.type !== 'discipline').sort((a, b) => (b.importance || 0) - (a.importance || 0)).slice(0, 5)
  return <><section className="map-intro"><p className="eyebrow">化学竞赛知识图谱</p><h1>知识网络总览</h1><p>从学科、概念和方法开始浏览。搜索可以定位知识节点或题目，节点详情会显示相邻关系和历年记录。</p></section><OverviewGraph data={data} /><section className="stats-strip"><div><strong>{data.statistics.totalNodes}</strong><span>知识节点</span></div><div><strong>{data.statistics.totalProblems}</strong><span>题目元数据</span></div><div><strong>{data.graph.edges.length}</strong><span>知识关系</span></div><div><strong>{data.exams.length}</strong><span>考试批次</span></div></section><div className="section-heading"><div><p className="eyebrow">节点列表</p><h2>常用主题</h2></div><Link to="/exams" className="text-link">查询真题</Link></div><section className="topic-grid">{topics.map(node => <button className="topic-card" key={node.id} onClick={() => navigate(`/knowledge/${node.id}`)}><span className="topic-icon" style={{ background: data.taxonomy.disciplines.find(d => d.id === node.discipline)?.color }}>{node.label.slice(0, 1)}</span><span><b>{node.label}</b><small>{data.taxonomy.disciplines.find(d => d.id === node.discipline)?.name} · {node.type === 'method' ? '方法' : '概念'}</small></span><span className="topic-action">查看</span></button>)}</section></>
}

function GraphView({ data }: { data: AppData }) {
  const container = useRef<HTMLDivElement>(null); const graph = useRef<cytoscape.Core | null>(null); const [selected, setSelected] = useState<GraphNode | null>(null); const navigate = useNavigate()
  useEffect(() => { if (!container.current) return; const cy = cytoscape({ container: container.current, elements: [...data.graph.nodes.map(node => ({ data: node })), ...data.graph.edges.map(edge => ({ data: edge }))], style: [{ selector: 'node', style: { 'background-color': (element: any) => data.taxonomy.disciplines.find(d => d.id === element.data('discipline'))?.color || '#5575b8', label: 'data(label)', color: '#183b4d', 'font-size': 10, 'text-wrap': 'wrap', 'text-max-width': 74, 'text-valign': 'bottom', 'text-margin-y': 8, width: (element: any) => element.data('type') === 'discipline' ? 48 : 32, height: (element: any) => element.data('type') === 'discipline' ? 48 : 32, 'border-width': 2, 'border-color': '#fff' } }, { selector: 'edge', style: { width: 1.5, 'line-color': '#aec0c5', 'target-arrow-shape': 'triangle', 'target-arrow-color': '#aec0c5', 'curve-style': 'bezier' } }, { selector: ':selected', style: { 'border-width': 4, 'border-color': '#f4a261' } }] as any, layout: { name: 'cose', animate: false, padding: 30 } }); graph.current = cy; cy.on('tap', 'node', event => setSelected(event.target.data() as GraphNode)); return () => { graph.current = null; cy.destroy() } }, [data])
  const reset = () => { graph.current?.fit(undefined, 30); graph.current?.center(); setSelected(null) }; const neighbors = selected ? data.graph.edges.filter(edge => edge.source === selected.id || edge.target === selected.id) : []
  return <><div className="page-title"><div><p className="eyebrow">知识关系</p><h1>知识图谱</h1><p>从学科总览进入具体节点，关系同时提供图形和文字列表。</p></div><div className="legend">{data.taxonomy.disciplines.map(discipline => <span key={discipline.id}><i style={{ background: discipline.color }} />{discipline.name}</span>)}</div></div><div className="graph-layout"><div className="graph-card"><div className="graph-toolbar"><span>{data.graph.nodes.length} 个节点 · {data.graph.edges.length} 条关系</span><button onClick={reset}>恢复总览</button></div><div ref={container} className="cy" aria-label="化学知识关系图" /><div className="graph-hint">选择节点后查看相邻关系；手机端可使用下方文字列表。</div></div><aside className="detail-panel">{selected ? <><p className="eyebrow">当前节点</p><h2>{selected.label}</h2><span className="pill" style={{ background: data.taxonomy.disciplines.find(d => d.id === selected.discipline)?.color }}>{data.taxonomy.disciplines.find(d => d.id === selected.discipline)?.name}</span><p className="panel-copy">该节点连接着先修内容、解题方法和历年考查记录。</p><h3>相邻关系 <small>{neighbors.length}</small></h3><ul className="relation-list">{neighbors.map(edge => { const other = data.graph.nodes.find(node => node.id === (edge.source === selected.id ? edge.target : edge.source)); return <li key={edge.id}><span className="relation-type">{data.taxonomy.relations.find(relation => relation.id === edge.relation)?.name || edge.relation}</span><button onClick={() => setSelected(other || null)}>查看 {other?.label}</button></li> })}</ul><button className="secondary full" onClick={() => navigate(`/knowledge/${selected.id}`)}>查看知识详情</button></> : <div className="empty-panel"><span className="empty-symbol">◎</span><h3>请选择节点</h3><p>节点连接着学科、方法和考试记录。选择后可查看文字关系。</p></div>}</aside></div></>
}

function Exams({ data }: { data: AppData }) { const params = new URLSearchParams(useLocation().search); const [stage, setStage] = useState('全部'); const [year, setYear] = useState('全部'); const [query, setQuery] = useState(params.get('q') || ''); const filtered = data.problems.filter(problem => { const exam = data.exams.find(item => item.id === problem.examId); return (stage === '全部' || exam?.stage === stage) && (year === '全部' || String(exam?.year) === year) && (!query || `${problem.title}${problem.number}`.includes(query)) }); return <><div className="page-title split"><div><p className="eyebrow">题目查询</p><h1>真题档案</h1><p>按年份、考试阶段和主题查看题目元数据与知识映射。</p></div><span className="archive-count">{filtered.length} <small>条记录</small></span></div><div className="filters"><input value={query} onChange={event => setQuery(event.target.value)} placeholder="筛选题号或主题" aria-label="筛选题目" /><select value={stage} onChange={event => setStage(event.target.value)}><option>全部</option><option>初赛</option><option>决赛</option></select><select value={year} onChange={event => setYear(event.target.value)}><option>全部</option>{[...new Set(data.exams.map(exam => exam.year))].sort().map(item => <option key={item}>{item}</option>)}</select></div><div className="exam-list">{filtered.map(problem => <ProblemCard key={problem.id} problem={problem} exam={data.exams.find(exam => exam.id === problem.examId)!} data={data} />)}</div></> }
function ProblemCard({ problem, exam, data }: { problem: Problem; exam: AppData['exams'][number]; data: AppData }) { return <Link to={`/exams/${problem.id}`} className="problem-card"><span className="problem-year">{exam.year}<small>{exam.stage}</small></span><span className="problem-main"><b>{problem.number} · {problem.title}</b><span>{problem.disciplines.map(id => data.taxonomy.disciplines.find(discipline => discipline.id === id)?.name).join(' / ')} · {problem.mappingCount} 个知识映射</span></span><span className="difficulty">难度 {problem.difficulty}/5</span><span className="problem-action">查看记录</span></Link> }

function Knowledge({ data }: { data: AppData }) { const { id } = useParams(); const node = data.graph.nodes.find(item => item.id === id) || data.graph.nodes.find(item => item.type !== 'discipline')!; const relations = data.graph.edges.filter(edge => edge.source === node.id || edge.target === node.id); const linked = data.problems.filter(problem => problem.disciplines.includes(node.discipline)); return <><Link to="/graph" className="back">← 返回知识图谱</Link><section className="knowledge-head"><span className="topic-icon large" style={{ background: data.taxonomy.disciplines.find(d => d.id === node.discipline)?.color }}>{node.label.slice(0, 1)}</span><div><p className="eyebrow">{data.taxonomy.disciplines.find(d => d.id === node.discipline)?.name} · {node.type === 'method' ? '解题方法' : '知识概念'}</p><h1>{node.label}</h1><p>节点 ID：{node.id} · 重要度 {node.importance || 3}/5</p></div></section><div className="knowledge-grid"><article className="article"><h2>知识说明</h2><p>本页汇总该知识点在竞赛资料中的位置、相邻关系和历年考查索引。讲义内容将在完成来源核验后逐步补充。</p><div className="notice"><span>ⓘ</span><div><b>公开范围：元数据</b><br />题目原文、参考答案和评分材料仍保存在受控资料库。</div></div><h2>相关真题</h2>{linked.map(problem => <Link className="mini-problem" to={`/exams/${problem.id}`} key={problem.id}><b>{data.exams.find(exam => exam.id === problem.examId)?.year} · {problem.number}</b><span>{problem.title}</span><span className="text-link">查看</span></Link>)}</article><aside className="side-card"><h3>关系清单 <small>{relations.length}</small></h3><ul className="relation-list">{relations.map(edge => { const other = data.graph.nodes.find(item => item.id === (edge.source === node.id ? edge.target : edge.source)); return <li key={edge.id}><span className="relation-type">{data.taxonomy.relations.find(relation => relation.id === edge.relation)?.name || edge.relation}</span><Link to={`/knowledge/${other?.id}`}>查看 {other?.label}</Link></li> })}</ul><h3>学习提示</h3><p className="muted">先阅读相邻节点，再回看题目中的综合考查关系。</p></aside></div></> }

function ExamDetail({ data }: { data: AppData }) { const { id } = useParams(); const problem = data.problems.find(item => item.id === id); if (!problem) return <NotFound />; const exam = data.exams.find(item => item.id === problem.examId)!; return <><Link to="/exams" className="back">← 返回真题档案</Link><section className="detail-title"><span className="problem-year big">{exam.year}<small>{exam.stage}</small></span><div><p className="eyebrow">{exam.title}</p><h1>{problem.number} · {problem.title}</h1><p>{problem.disciplines.map(discipline => data.taxonomy.disciplines.find(item => item.id === discipline)?.name).join(' / ')} · 难度 {problem.difficulty}/5</p></div></section><div className="notice wide"><span>ⓘ</span><div><b>题文暂不公开</b><br />{problem.summary} 来源：{exam.sourceLabel}。</div></div><section className="detail-columns"><article><h2>考查结构</h2><div className="mapping-box">{data.graph.nodes.filter(node => problem.disciplines.includes(node.discipline) && node.type !== 'discipline').slice(0, problem.mappingCount).map(node => <Link to={`/knowledge/${node.id}`} key={node.id}><span style={{ background: data.taxonomy.disciplines.find(d => d.id === node.discipline)?.color }}>{node.label.slice(0, 1)}</span><b>{node.label}</b><small>{node.type === 'method' ? '解题方法' : '知识概念'}</small></Link>)}</div></article><aside className="source-card"><h3>来源记录</h3><dl><dt>公开状态</dt><dd>metadata_public</dd><dt>题目编号</dt><dd>{problem.id}</dd><dt>资料来源</dt><dd>{exam.sourceLabel}</dd><dt>知识映射</dt><dd>{problem.mappingCount} 个</dd></dl><Link to="/about" className="text-link">查看来源规范</Link></aside></section></> }

function Statistics({ data }: { data: AppData }) { const max = Math.max(...data.statistics.yearCounts.map(item => item.value), 1); return <><div className="page-title"><div><p className="eyebrow">资料统计</p><h1>统计研究</h1><p>从公开元数据查看题目覆盖与知识分布，数据会随审核批次更新。</p></div></div><section className="metric-grid"><div><span>知识节点</span><strong>{data.statistics.totalNodes}</strong><small>当前公开版本</small></div><div><span>题目元数据</span><strong>{data.statistics.totalProblems}</strong><small>初赛与决赛</small></div><div><span>关系数量</span><strong>{data.graph.edges.length}</strong><small>可追溯关系</small></div></section><div className="charts"><section className="chart-card"><h2>学科覆盖</h2><div className="bars">{data.statistics.disciplineCounts.map(item => <div className="bar-row" key={item.name}><span>{item.name}</span><div><i style={{ width: `${Math.max(8, item.value / 3 * 100)}%`, background: item.color }} /></div><b>{item.value}</b></div>)}</div></section><section className="chart-card"><h2>年份样本</h2><div className="year-chart">{data.statistics.yearCounts.map(item => <div key={item.year}><div className="column" style={{ height: `${item.value / max * 150}px` }}><b>{item.value}</b></div><span>{item.year}</span></div>)}</div></section></div><p className="data-note">ⓘ {data.statistics.note}</p></> }

function About() { const formula = katex.renderToString(String.raw`\ce{2H2 + O2 -> 2H2O}`, { throwOnError: false }); return <><div className="page-title"><div><p className="eyebrow">资料说明</p><h1>来源与方法</h1><p>这里说明公开范围、来源记录和知识标注方法。</p></div></div><div className="about-grid"><article className="article"><h2>公开内容</h2><p>网站发布考试年份、题号、主题、知识映射和来源索引等元数据。未经授权的题目原文、答案、扫描件和内部文件不会发布。</p><h2>知识标注</h2><p>题目录入按“考试—整题—小问—知识节点—关系”组织。新节点进入人工审核队列；每条映射保留来源文件哈希、页码和审核状态。</p><p className="formula" aria-label="化学方程式排版示例" dangerouslySetInnerHTML={{ __html: formula }} /><h2>资料状态</h2><div className="status-list"><div><i className="dot green" /><b>metadata_public</b><span>可公开元数据</span></div><div><i className="dot amber" /><b>internal_only</b><span>仅本地管理台可见</span></div><div><i className="dot blue" /><b>fulltext_authorized</b><span>取得授权后可展示全文</span></div></div></article><aside className="side-card"><h3>数据版本</h3><p className="data-version">2026.08-demo</p><p className="muted">当前版本用于展示网站结构和查询方式，题目录入工作按批次进行。</p><hr /><h3>建议引用</h3><p className="muted">化学竞赛知识图谱，数据版本 2026.08。</p></aside></div></> }
function NotFound() { return <div className="empty-page"><h1>没有找到这条记录</h1><Link to="/">返回总览</Link></div> }
export default function App({ data }: { data: AppData }) { return <Shell data={data}><Routes><Route path="/" element={<Home data={data} />} /><Route path="/graph" element={<GraphView data={data} />} /><Route path="/exams" element={<Exams data={data} />} /><Route path="/exams/:id" element={<ExamDetail data={data} />} /><Route path="/knowledge/:id" element={<Knowledge data={data} />} /><Route path="/statistics" element={<Statistics data={data} />} /><Route path="/about" element={<About />} /><Route path="*" element={<NotFound />} /></Routes></Shell> }
